### ISSUE TITLE
Cookies aren't being defined using `@elysiajs/cookie` package

### ISSUE THREAD

**Issue by iagocalazans** [bogeychan/elysia-oauth2#8]
I'm trying to set cookies using `@elysiajs/cookie` but they are never sent out.

```ts
 ...
 .use(cookie({
    maxAge: 3600,
    signed: true,
    secret: ['Some Secret To Sign']
  })
 ...
```

Then in `storage.set` I use the setCookie method from `@elysiajs/cookie`:
```ts
 set ({setCookie}, name, token) {
   setCookie(`t_session`, 'some_cookie_value', { maxAge: token.expires_in });
   return token;
 }
```

It only works when I change the code sent in PR #7

**Comment by bogeychan** [comment]
Hi 👋, as I've said here you need to set the cookie-`path`: https://github.com/bogeychan/elysia-oauth2/pull/7#issuecomment-1751822805

i forgot to mention that as of elysia version 0.7.x the cookie plugin is deprecated and integrated into the core library. so instead of using the plugin you have to do it as described here: https://elysiajs.com/patterns/cookie.html

**Comment by iagocalazans** [comment]
Many thanks! 🫡
